FROM ubuntu:20.04
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list && \
 apt-get update && \
 apt-get --no-install-recommends install -y openjdk-8-jre-headless && \
 rm -rfv /var/lib/apt/lists/*