From golang:1.4.2 as builder

ADD hello.go hello.go
RUN go build hello.go

From scratch

COPY --from=builder /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libpthread.so.0
COPY --from=builder /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=builder /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=builder /go/hello hello

EXPOSE 8080
ENTRYPOINT ["./hello"]